[env:display_arduino]
platform = atmelavr
board = nanoatmega328
framework = arduino

; 1. Den exakten Chip erzwingen
board_build.mcu = atmega328p
board_build.f_cpu = 16000000L

; 2. Das Protokoll für Old Bootloader präzisieren
upload_protocol = arduino
upload_speed = 57600

; 3. Port auf den Wert aus deinem dmesg-Log anpassen
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 9600

; 4. Filter und Libs (bleiben gleich)
build_src_filter = -<*> +<test.cpp>
lib_deps = 
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  adafruit/Adafruit BusIO
  Wire